# Add a basic subproject
add_executable(StaticKeyword static_keyword.cpp)
add_executable(Aggregiation aggregation.cpp)
add_executable(LambdaExp lambda_expression.cpp)
add_executable(MultiThread multi_thread.cpp)
add_executable(ArrayManipulation array_manipulation.cpp)
add_executable(MemoryManagement memory_management.cpp)
add_executable(MoveSemantics move_semantics.cpp)
